### ISSUE TITLE
Ini file for the scripts

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/dev-tools#15]
In the laudable tradition of Bash I suggest we have a _default_ ini which contains

```
editor_path=C:\program Files\notepad++\notepad++.exe
skyrim_latest_thread=897896708
skyrim_prev_thread=876876869
oblivion_latest_thread=7777
oblivion_prev_thread=6666
# etc
```

And other such options for easy editing - those options would be awkward to pass as arguments to the scripts. I would appreciate someone writing (and committing in a branch)  a kickoff module for reading this ini. The options would be overridden in a user ini and read from the default ONLY if the user hasn't overridden them.

The more I work with the scripts the more an ini such as this becomes a necessity - that's why I tag this bug.

**Comment by Infernio** [comment]
Closed in ba02dfd00717632fccd5fea17de2345b1c592bd2
