### ISSUE TITLE
Extend the scripts (changelog, automatic version history, second post etc)

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/dev-tools#17]
@lojack5 I managed to write a changelog thingy which does not do much but it's a start: https://github.com/wrye-bash/meta/tree/utumno-changelog/SecondPosts. Output (edit 2014.03.28):

```
<h2>304.4 [2014/03/28] ['Various community members']</h2>
<ul>
    <li>Optimize PNGs [Metallicow]</li>
    <li>Remove the auto-updater [lojack5]</li>
    <li>Skip .bsl files for BAIN [lojack5]</li>
    <li>BOSSv3 support, installer and readme updates [WrinklyNinja]</li>
    <li>Installer Improvements [WrinklyNinja]</li>
    <li>Installer MSVC 2013 Redist Support [WrinklyNinja]</li>
    <li>Missing context menu items [WrinklyNinja]</li>
    <li>Show BSA Conflicts undocumented [WrinklyNinja]</li>
</ul>
```

I broke your code in modules to reuse it
- the github_wrapper module is fine, maybe rethinking `skip_labels` parameters - <del>could be the labels we are interested in</del> -> we need a builder for issue lists, see code comments in getIssues()
- the html module is fine too I think - maybe rename to formatting ?
- the globals module has our wrye-bash/wrye-bash specific info and wraps the github for our repo - I marked its functions as _private (so subject to change)
- if we go down that road we will need a templates/ subdir (to put stuff like generate_second_posts_lines.txt and .usr)
- I am sure I did unpythonisms (and I miss toString())

What you say in all ?

(that's 305+ really)

EDIT: 
 These steps from the release guide(https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Making-A-Release):
- [x] Update Wrye Bash Version History.html with this change log.
- [x] Update the same file in the Online Readme
- [x] Update the Skyrim/Oblivion/etc first posts with the new change log and version in the meta repository.
- [x] ~~Update the Skyrim/Oblivion/etc Nexus Description page templates in meta with the new change log and version.~~
- [x] master commit message / release changelog --> that's the generate_cahngelog.writeChangelogBBcode() method

need automation.

Also
- [x]  CLI Parser module

**Comment by Infernio** [comment]
Closed in 7f6f7b83723cdf7f32dc1d8d30cf15124775de9c.
