### ISSUE TITLE
Do we need this repo ?

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/dev-tools#3]
Wanted to push the editor files I am ripping from wrye-Bash somewhere and before I open a branch here (and make dirs like editors/eclipse-pydev, editors/pycharm etc) I want us to discuss a bit what's to be in here - and do we really need this repo ? Or could we just make a dev-tools folder in the meta repo and be done with it ? Not sure, but I'd say merge those two and be done with it - but I might be missing something

**Comment by Infernio** [comment]
Closing - resolution is that we transfer the changelog script from meta to dev-tools, then keep dev-tools and delete meta.
